.\" Copyright (c) 2015 Mark Otaris <mark.otaris@openmailbox.org>
.\" Copyright (c) 2017 John M Harris, Jr. <johnmh@openblox.org>
.\"
.\" This file is part of OpenBlox Studio.
.\"
.\" OpenBlox Studio is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" OpenBlox Studio is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with OpenBlox Studio.  If not, see <http://www.gnu.org/licenses/>.
.\"
.TH OPENBLOX-STUDIO 1 2017-03-20 "OpenBlox Studio" "OpenBlox User's Manual"
.SH NAME
openblox-studio \- Integrated development environment for the OpenBlox game engine.
.SH SYNOPSIS
.BI "openblox-studio [" options "] [" arguments "] "
.SH DESCRIPTION
OpenBlox is aimed towards providing a Lua API similar to that of ROBLOX
to enable developers to create games faster and with less restrictions.

OpenBlox Studio is an integrated development environment intended for
the creation of games usable with the OpenBlox game engine.
.SH OPTIONS
.IP "-h, --help"
Display this help.
.IP "-v, --version"
Display version information.
.SH EXIT STATUS
This program exits with 0 on success and 1 on failure.
.SH BUGS
The list of known bugs is available at <https://bugs.openblox.org/>.
This is also where you can report bugs you find while using the program.
.SH EXAMPLE
.IP "openblox-studio path/to/game.obgx"
Start OpenBlox Studio and open the game 'game.obgx'
.SH AUTHOR
John M. Harris, Jr. (johnmh@openblox.org)
